---
- name: restart mysql
  ansible.builtin.service:
    name: mysql
    state: restarted
    enabled: true

- name: restart fpm
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: restarted

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: restart cron
  ansible.builtin.service:
    name: cron
    state: restarted
