---
- name: Converge

  hosts: all

  become: true

  pre_tasks:

    - name: update apt cache.
      apt:
        update_cache: yes
      when: (ansible_os_family | lower) == 'debian'
      failed_when: false
      ignore_errors: true
      changed_when: false

    - name: remove dockerenv
      file:
        path: /.dockerenv
        state: absent

  roles:

    - name: wpnops.librenms
      vars:
        configure: true
