---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2004}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      all:
        librenms_root: /opt/librenms
        librenms_user: librenms
        librenms_admin_user: librenms
        librenms_admin_pass: librenms
        librenms_admin_token: e9bab3639db475105f6eb41b969e7cc4
        librenms_db_name: librenms
        librenms_api_uri: http://localhost/api/v0
verifier:
  name: ansible
scenario:
  name: default
