---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest
    tmpfs:
      - /run
      - /tmp
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - SYS_ADMIN
    command: ${MOLECULE_IMAGE_COMMAND:-"/lib/systemd/systemd"}
    pre_build_image: true
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - side_effect
    - verify
    - cleanup
    - destroy
provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      all:
        librenms_root: /opt/librenms
        librenms_user: librenms
        librenms_db_user: librenms
        librenms_db_pass: librenms
        librenms_db_name: librenms
verifier:
  name: ansible
