---
- name: side effect

  hosts: all

  become: true

  tasks:

    - name: take librenms backup
      command: /usr/local/bin/librenms-backup
      register: _backup_script
      until: _backup_script is not failed
      retries: 5
      delay: 5

    - name: kill mysql connections
      command: |
        mysql -u {{ librenms_db_user }} -D {{ librenms_db_name }} -p{{ librenms_db_pass }}
        -e "select concat('KILL ',id,';') from information_schema.processlist"

    - name: drop librenms database
      command: |
        mysql -u {{ librenms_db_user }} -p{{ librenms_db_pass }}
        -e "drop database {{ librenms_db_name }};"

    - name: confirm database does not exist
      command: |
        mysql -u {{ librenms_db_user }} -p{{ librenms_db_pass }} \
        -e "show databases;"
      register: _database_output

    - name: debug librenms database output
      debug:
        var: _database_output.stdout_lines

    - name: verify librenms status after dropping database
      command: "{{ librenms_root }}/validate.php"
      become_user: "{{ librenms_user }}"
      failed_when: false
      register: _librenms_healthcheck_result

    - name: debug librenms healthcheck result
      debug:
        var: _librenms_healthcheck_result.stderr_lines

    - name: perform librenms restore
      command: /usr/local/bin/librenms-restore
      register: _restore_script
      until: _restore_script is not failed
      retries: 5
      delay: 5
